export const projects = [
    {
        id: 1,
        title: 'GitHub Issue Tracker',
        description: 'Full-featured issue tracker using GitHub REST API. Features include real-time filtering, sorting, pagination with page caching, drag-and-drop Kanban board, and favorites system with localStorage persistence. Built with modern React patterns and TypeScript.',
        tech: ['React', 'TypeScript', 'React Query', 'Tailwind CSS', 'DnD Kit'],
        imgs: ['./../../../public/images/issueTracker1.png', './../../../public/images/issueTracker2.png'],
        github: 'https://github.com/yazanabdalrazak26-del/issue-tracker',
    },
    {
        id: 2,
        title: 'TMDB Movie Search',
        description: 'Movie and TV show discovery app with infinite scroll, virtual scrolling for performance, responsive grid layout, and real-time search. Integrated TMDB API with React Query caching. Features include filtering by media type, rating display, and detailed view for each title.',
        tech: ['React', 'TanStack Query', 'Tailwind CSS', 'TMDB API', 'React Query'],
        imgs: ['./../../../public/images/movie2.png', './../../../public/images/movie4.png', './../../../public/images/movie5.png', './../../../public/images/movie6.png','./../../../public/images/movie7.png'],
        github: 'https://github.com/yazanabdalrazak26-del/tmdb-movie-website.git',
    },
    {
        id: 3,
        title: 'E-Commerce Store',
        description: 'Basic e-commerce platform with product catalog, shopping cart, and checkout page. Built as a learning project to understand React fundamentals. Features product filtering by category, quantity selection, and cart total calculation. Note: This project is archived and not actively maintained. [Legacy Project - Not Maintained]',
        tech: ['React', 'Context API', 'React Router', 'CSS Modules' , 'React Redux'],
        github: 'https://github.com/yazanabdalrazak26-del/e-commerce-website',
        imgs: ['./../../../public/images/e1.png' , './../../../public/images/e2.png', './../../../public/images/e3.png', './../../../public/images/e4.png'],
        demo: 'https://e-commerce-website.vercel.app',
        archived: true,
    },
    {
        id: 4,
        title: 'Tenant Website',
        description: 'Property management platform for landlords and tenants. Features include tenant profiles, rent collection tracking, maintenance requests, [Ongoing]',
        tech: ['React', 'DnD Kit', 'Tailwind CSS', 'LocalStorage'],
        imgs: ['./../../../public/images/ten1.png' , './../../../public/images/ten2.png', './../../../public/images/ten3.png', './../../../public/images/ten4.png', './../../../public/images/ten5.png', './../../../public/images/ten6.png' ,'./../../../public/images/ten7.png'],
        github: 'https://github.com/yazanabdalrazak26-del/Tenant-website.git',
    },
];